[font]
size = 12.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[window]
opacity = 0.8

[general]
import = [
    "~/.config/alacritty/themes/tokyo-night.toml"
]
