keymap:
  - name: modifier_avell
    remap:
      #pont-virgula
      KEY_RO: key_slash
      # 2 pontos
      shift-KEY_RO: key_rightshift-key_slash
      # slash
      KEY_slash: key_ro
    device:
      only: ["/dev/input/event3", "/dev/input/event13"]

